[workspace]
members = [
    "examples/*",
    "fuzz",
    "imgt-update",
    "imgt",
    "mzalign",
    "mzannotate",
    "mzcore-update",
    "mzcore",
    "mzcv",
    "mzident",
    "rustyms-generate-databases",
    "rustyms-py",
]
resolver = "2"
package.authors = [
    "Douwe Schulte <d.schulte@uu.nl>",
    "Ralf Gabriels",
    "Auke Heerdink",
]
package.edition = "2024"
package.license = "MIT OR Apache-2.0"
package.rust-version = "1.88.0"

[profile.release]
debug = true
opt-level = 3
lto = true
codegen-units = 1

[workspace.dependencies]
afl = ">0.15, <=0.18"
base64 = ">0.15, <=0.23"
bincode = { version = "2.0", features = ["serde"] }
chrono = "0.4"
clap = { version = "4.6", features = ["derive", "cargo"] }
context_error = { git = "https://github.com/douweschulte/context_error", features = ["serde"] }
directories = "6.0"
flate2 = "1.0"
indexmap = "2.11"
itertools = ">0.12, <=0.15"
mzdata = { version = ">0.59, <=0.65", default-features = false, features = ["nalgebra"] }
num-traits = ">0.2.15, <=0.2"
ndarray = "0.17"
ordered-float = { version = "5.0", features = ["serde"] }
paste = ">1.0.5"
png = "0.18"
probability = "0.20"
pyo3 = "0.29"
rand = "0.9"
rayon = ">1.0, <=1.12"
reqwest = { version = "0.13", features = ["blocking"] }
roxmltree = "0.21"
serde = { version = ">1.0.150, <=1.0", features = ["derive", "rc"] }
serde_json = "1.0"
sha2 = "0.11"
swash = "0.2"
thin-vec = { version = ">0.2.10, <=0.2", features = ["serde"] }
uom = { version = ">0.32, <=0.38", default-features = false, features = [
    "use_serde",
    "usize",
    "isize",
    "f64",
    "f32",
    "i8",
] }
zeno = { version = "0.3.2" }

[patch.crates-io]
#context_error = { path = "../context_error" }

[workspace.lints.rust]
ambiguous_negative_literals = "warn"
ambiguous_glob_reexports = "deny"
clashing_extern_declarations = "deny"
const_item_mutation = "deny"
dangling_pointers_from_temporaries = "deny"
deref_nullptr = "deny"
drop_bounds = "deny"
future_incompatible = "deny"
hidden_glob_reexports = "deny"
improper_ctypes = "deny"
improper_ctypes_definitions = "deny"
invalid_from_utf8 = "deny"
invalid_macro_export_arguments = "deny"
invalid_nan_comparisons = "deny"
invalid_reference_casting = "deny"
invalid_value = "deny"
keyword_idents = "warn"
let_underscore = "warn"
macro_use_extern_crate = "warn"
meta_variable_misuse = "warn"
missing_docs = "warn"
missing_abi = "warn"
missing_copy_implementations = "warn"
missing_debug_implementations = "warn"
noop_method_call = "warn"
opaque_hidden_inferred_bound = "deny"
overlapping_range_endpoints = "deny"
redundant_imports = "warn"
redundant_lifetimes = "warn"
single_use_lifetimes = "warn"
suspicious_double_ref_op = "deny"
trivial_casts = "warn"
trivial_numeric_casts = "warn"
unconditional_recursion = "deny"
unexpected_cfgs = { level = "allow", check-cfg = [
    "cfg(f32)",
    "cfg(github_action)",
    "cfg(si)",
] }
unnameable_test_items = "deny"
unnameable_types = "warn"
unreachable_pub = "deny"
unsafe_op_in_unsafe_fn = "deny"
unstable_syntax_pre_expansion = "deny"
unused = { level = "warn", priority = -1 }
unused_crate_dependencies = "warn"
unused_extern_crates = "warn"
unused_imports = "warn"
unused_import_braces = "warn"
unused_lifetimes = "deny"
unused_qualifications = "warn"
variant_size_differences = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
cast_possible_truncation = "allow"
cast_precision_loss = "allow"
cast_sign_loss = "allow"
module_name_repetitions = "allow"
must_use_candidate = "allow"
redundant_pub_crate = "allow"
too_long_first_doc_paragraph = "allow"
too_many_lines = "allow"
wildcard_imports = "allow"
literal_string_with_formatting_args = "allow"
unsafe_derive_deserialize = "allow"
unreadable_literal = "allow"
cognitive_complexity = "allow"
module_inception = "allow"
unwrap_in_result = "warn"
panic_in_result_fn = "warn"

#too_many_arguments = "allow"
#type_complexity = "allow"
#missing_panics_doc = "allow"